# SLF4J Simple Logger configuration for the sample
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss.SSS
# Global default
org.slf4j.simpleLogger.defaultLogLevel=INFO
# Tune Camel logs
org.slf4j.simpleLogger.log.org.apache.camel=INFO
org.slf4j.simpleLogger.log.io.dscope.camel=DEBUG
